db:
  image: mysql:latest
  environment:
    MYSQL_ROOT_PASSWORD: nimda
    MYSQL_DATABASE: example_db
    MYSQL_USER: example_db_user
    MYSQL_PASSWORD: example_db_pass
#  ports:
#    - "3306:3306"
  volumes:
   - ./script:/docker-entrypoint-initdb.d

web:
  image: tomcat:9
  # Environment variables do not appear to be getting loaded the first time Tomcat starts!
  environment:
    JDBC_URL: jdbc:mysql://db:3306/example_db?connectTimeout=0&amp;socketTimeout=0&amp;autoReconnect=true
    JDBC_USER: example_db_user
    JDBC_PASS: example_db_pass
  ports:
   - "8080:8080"
  volumes:
   - ./tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
   - ./target/pokerserver.war:/usr/local/tomcat/webapps/pokerserver.war
   - ./conf/web.xml:/usr/local/tomcat/conf/web.xml
  links:
    - db
